[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pr_2 = "AfgNW3h4kkE6GW8T2c3JxxropMLPTsQjhJMPQJqH4VbZ"

[programs.devnet]
pr_2 = "AfgNW3h4kkE6GW8T2c3JxxropMLPTsQjhJMPQJqH4VbZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/zeroday/Desktop/zerospace/solana/practive/pr-2/keys/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
